[package]
name = "k21-screen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
image = "0.25.5"
xcap = "0.3.2"
tokio = { version = "1.43", features = ["full", "tracing"] }
clap = { version = "4.5.30", features = ["derive"] }
log = "0.4.25"
env_logger = "0.11.6"
humantime = "2.1.0"
glob = "0.3.2"
