version: '3.8'

services:
  # Development configuration
  k21-server-dev:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    restart: unless-stopped
    profiles:
      - dev

  # Production configuration
  k21-server-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
      platforms:
        - linux/amd64
      args:
        - BUILDPLATFORM=linux/amd64
        - TARGETPLATFORM=linux/amd64
    image: europe-west10-docker.pkg.dev/kontext21-cloud/kontext21-cloud/k21-server:latest
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
    restart: unless-stopped
    profiles:
      - prod
