name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-on-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build release
      run: cargo build --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build-release
        path: target/release/*.exe
        overwrite: true

  build-on-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: brew install tesseract pkg-config
    - name: Build
      run: cargo build --verbose
    - name: Build release
      run: cargo build --release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build-release
        path: target/release/*
        overwrite: true

  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      id: meta
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.prod
        push: ${{ github.event_name != 'pull_request' }}
        tags: ghcr.io/${{ github.repository }}:latest

    - name: Push buildcache separately (to prevent overriding the main image)
      if: ${{ github.event_name != 'pull_request' && github.ref == format('refs/heads/{0}', 'main') }}
      run: |
        docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:buildcache
        docker push ghcr.io/${{ github.repository }}:buildcache
